---
- hosts: all
  become: true
  tasks:
    - name: "Instalacao do MariaDB SERVER via YUM"
      yum: name=mariadb-server state=present update_cache=yes
 
    - name: "MYSQL started"
      service: name=mariadb state=started enabled=yes
